csdn:
  api:
    categories: Java场景面试宝典
    cookie: uuid_tt_dd=10_30706389210-1764042207244-777084; UserName=A_ABai; UserToken=28cf4e40527447778e21b77f29a9acc9;

spring:
  application:
    name: okk-mcp-server-csdn

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    banner-mode: off
# stdio 模式打开，sse 模式，注释掉。
#    web-application-type: none

logging:
  # stdio 模式打开，sse 模式，注释掉。
  #  pattern:
  #    console:
  file:
    name: data/log/${spring.application.name}.log

server:
  port: 8101
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true